# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskType', models.IntegerField()),
                ('taskUrl', models.CharField(max_length=10240)),
                ('taskStartTime', models.DateTimeField(null=True)),
                ('taskFilesize', models.IntegerField(default=0)),
                ('taskFilename', models.CharField(max_length=200)),
                ('taskHash', models.CharField(max_length=200)),
                ('taskRate', models.IntegerField(default=0)),
                ('taskCompletedTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('diskSpaceLimit', models.IntegerField(default=20480)),
                ('taskNumberLimit', models.IntegerField(default=10)),
                ('usedDiskSpace', models.IntegerField(default=0)),
                ('usedTaskNumber', models.IntegerField(default=0)),
                ('savetimeLimit', models.IntegerField(default=72)),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offDown.Users'),
        ),
    ]
