# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offDown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskGid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskFilename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskHash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskUrl',
            field=models.CharField(max_length=10240, null=True),
        ),
    ]
