# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offDown', '0002_auto_20160214_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='keepaliveHash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
