# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offDown', '0003_users_keepalivehash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskActive',
            field=models.IntegerField(default=0),
        ),
    ]
