# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offDown', '0004_tasks_taskactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskSpeed',
            field=models.IntegerField(default=0),
        ),
    ]
