# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offDown', '0005_tasks_taskspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
