# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offDown', '0006_tasks_taskname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskStatus',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
