# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offDown', '0007_tasks_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskDelFailed',
            field=models.BooleanField(default=False),
        ),
    ]
