# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offDown', '0008_tasks_taskdelfailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskDelFailed',
            field=models.IntegerField(default=0),
        ),
    ]
